{
 "title": "Kafka Monitoring",
 "description": "Kafka Monitoring",
 "tags": [
  "kafka",
  "influxdb"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "influxdb" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "SHOW TAG VALUES FROM \"kafka_controller_KafkaController_Value\" WITH KEY = \"project_name\""
   },
   { "name": "side", "label": "DR Side", "query": "left,right" },
   {
    "name": "broker",
    "label": "Broker",
    "query": "SHOW TAG VALUES FROM \"kafka_controller_KafkaController_Value\" WITH KEY = \"broker\" WHERE \"broker\"=~/$side.*/"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "description": "Current status of Kafka cluster",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"status\") FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Size",
   "type": "singlestat",
   "description": "Current size of Kafka cluster",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"size\") FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller State",
   "type": "singlestat",
   "description": "Current state of controller broker. The controller changes state when processing an event. Most of the time, the Idle state is displayed, which means that the controller has processed all the events. If the event processing takes a considerable time (several seconds or more), this state of the controller will be displayed",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"gauge\") FROM \"kafka_controller_KafkaController_Value\" WHERE \"name\" = 'ControllerState' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller Broker",
   "type": "singlestat",
   "description": "Current controller broker.\nThe first node to boot in a Kafka cluster automatically becomes the controller, and there can be only one. The controller in a Kafka cluster is responsible for maintaining the list of partition leaders, and coordinating leadership transitions (in the event a partition leader becomes unavailable). If it becomes necessary to replace the controller, a new controller is randomly chosen by ZooKeeper from the pool of brokers. In general, it is not possible for this value to be greater than one, but you should definitely alert on a value of zero",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"kafka_controller_KafkaController_ActiveControllerBroker\" WHERE \"gauge\" = 1 AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kafka Version",
   "type": "singlestat",
   "description": "Kafka version running on controller broker",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"version\") FROM \"kafka_server_app_info_Version\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Status Transitions",
   "type": "graph",
   "description": "Transitions of Kafka cluster statuses. Where :\n10 - DOWN;\n6 - DEGRADED;\n0 - UP.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "UP  -  DEGRADED  -  DOWN" }
   ],
   "targets": [
    {
     "alias": "cluster_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"status\" FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller State Transitions",
   "type": "graph",
   "description": "Transitions of controller broker states. The controller changes state when processing an event. Most of the time, the Idle state is displayed, which means that the controller has processed all the events. If the event processing takes a considerable time (several seconds or more), this state of the controller will be displayed. Where:\n16 - Update Metadata Response Received;\n15 - List Partition Reassignment;\n14 - Topic Unclean Leader Election Enable;\n13 - Unclean Leader Election Enable;\n12 - Controller Shutdown;\n11 - Log Dir Change;\n10 - Leader And Isr Response Received;\n9 - Isr Change;\n8 - Controlled Shutdown;\n7 - Manual Leader Balance;\n6 - Auto Leader Balance;\n5 - Alter Partition Reassignment;\n4 - Topic Deletion;\n3 - Topic Change;\n2 - Broker Change;\n1 - Controller Change;\n0 - Idle.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "controller_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"gauge\" FROM \"kafka_controller_KafkaController_Value\" WHERE \"name\" = 'ControllerState' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Similar Configs",
   "type": "singlestat",
   "description": "Information about brokers configuration consistency",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"same_configs\") FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "table",
   "description": "Information about broker states, number of partitions replicas on each broker, number of partitions where current broker is a leader, skews and number of under replicated partitions",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"broker_state\") AS \"broker_state\", max(\"partition_count\") AS \"partition_count\", max(\"broker_skew\") AS \"broker_skew\", max(\"leader_count\") AS \"leader_count\", max(\"broker_leader_skew\") AS \"broker_leader_skew\", max(\"under_replicated_partitions\") AS \"under_replicated_partitions\", max(\"under_min_isr_partition_count\") AS \"under_min_isr_partition_count\" FROM \"kafka\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY \"broker\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Topics Count",
     "type": "singlestat",
     "description": "Total number of topics on Kafka cluster",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"gauge\") FROM \"kafka_controller_KafkaController_Value\" WHERE \"name\" = 'GlobalTopicCount' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Partitions Count",
     "type": "singlestat",
     "description": "Total number of partitions on Kafka cluster",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"gauge\") FROM \"kafka_controller_KafkaController_Value\" WHERE \"name\" = 'GlobalPartitionCount' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "singlestat",
     "description": "Number of partitions without an active leader. Because all read and write operations are only performed on partition leaders, a non-zero value for this metric should be alerted on to prevent service interruptions. Any partition without an active leader will be completely inaccessible, and both consumers and producers of that partition will be blocked until a leader becomes available",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"kafka_controller_KafkaController_Value\" WHERE \"name\" = 'OfflinePartitionsCount' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Topics Without Leader",
     "type": "singlestat",
     "description": "List of topics which have at least one partition without a leader",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"topics_without_leader\") AS \"TopicsWithoutLeader\" FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Under Replicated Topics",
     "type": "singlestat",
     "description": "List of topics which have at least one under replicated partition",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"under_replicated_topics\") AS \"UnderReplicatedTopics\" FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Unclean Leader Election Count",
     "type": "graph",
     "description": "Count of unclean leader elections since Kafka start",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Unclean Leader Elections",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"kafka_controller_ControllerStats_Value\" WHERE \"name\" = 'UncleanLeaderElectionsPerSec' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Topics With Unclean Leader Election Enabled",
     "type": "singlestat",
     "description": "List of topics with unclean leader election enabled. Unclean leader elections can lead to data loss, so you should check these topics to see if this setting is set reasonably",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"topics_with_unclean_leader_election\") AS \"TopicsWithUncleanLeaderElection\" FROM \"kafka_cluster\" WHERE \"project_name\" =~ /^$namespace$/ AND \"host\" =~ /^$side.*/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Groups Number",
     "type": "table",
     "description": "Number of consumer groups in different states",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"NumGroups\") AS \"Total\", max(\"NumGroupsStable\") AS \"Stable\", max(\"NumGroupsPreparingRebalance\") AS \"PreparingRebalance\", max(\"NumGroupsCompletingRebalance\") AS \"CompletingRebalance\",  max(\"NumGroupsEmpty\") AS \"Empty\", max(\"NumGroupsDead\") AS \"Dead\" FROM (SELECT \"project_name\", \"broker\", \"gauge\" AS \"NumGroups\" FROM \"kafka_coordinator_group_GroupMetadataManager_Value\" WHERE \"name\" = 'NumGroups'), (SELECT \"project_name\", \"broker\", \"gauge\" AS \"NumGroupsStable\" FROM \"kafka_coordinator_group_GroupMetadataManager_Value\" WHERE \"name\" = 'NumGroupsStable'), (SELECT \"project_name\", \"broker\", \"gauge\" AS \"NumGroupsPreparingRebalance\" FROM \"kafka_coordinator_group_GroupMetadataManager_Value\" WHERE \"name\" = 'NumGroupsPreparingRebalance'), (SELECT \"project_name\", \"broker\", \"gauge\" AS \"NumGroupsCompletingRebalance\" FROM \"kafka_coordinator_group_GroupMetadataManager_Value\" WHERE \"name\" = 'NumGroupsCompletingRebalance'), (SELECT \"project_name\", \"broker\", \"gauge\" AS \"NumGroupsEmpty\" FROM \"kafka_coordinator_group_GroupMetadataManager_Value\" WHERE \"name\" = 'NumGroupsEmpty'), (SELECT \"project_name\", \"broker\", \"gauge\" AS \"NumGroupsDead\" FROM \"kafka_coordinator_group_GroupMetadataManager_Value\" WHERE \"name\" = 'NumGroupsDead') WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Heap and GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Usage",
     "type": "graph",
     "description": "JVM heap usage by broker",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_broker: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"used\") AS \"used\", max(\"max\") AS \"limit\" FROM \"java_Memory_HeapMemoryUsage\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "JVM Heap Usage in Percent",
     "type": "graph",
     "description": "JVM heap usage by broker in percent (%)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT 100 * max(\"used\") / max(\"max\") FROM \"java_Memory_HeapMemoryUsage\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "description": "Garbage collection time rate per Sampling interval by broker",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_broker: young",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"java_GarbageCollector_CollectionTime\" WHERE \"name\" = 'G1 Young Generation' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_broker: old",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"java_GarbageCollector_CollectionTime\" WHERE \"name\" = 'G1 Old Generation' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "description": "Garbage collections count rate per Sampling interval by broker",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker: young",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"java_GarbageCollector_CollectionCount\" WHERE \"name\" = 'G1 Young Generation' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_broker: old",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 AS \"old\" FROM \"java_GarbageCollector_CollectionCount\" WHERE \"name\" = 'G1 Old Generation' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Memory usage by pod",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_pod_name: usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(value) FROM \"memory/usage\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" =~ /^$namespace$/ AND \"pod_name\" =~ /^$side.*/ AND \"pod_name\" =~ /$broker.*/ AND $timeFilter GROUP BY time($__interval), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_pod_name: limit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(value) FROM \"memory/limit\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" =~ /^$namespace$/ AND \"pod_name\" =~ /^$side.*/ AND \"pod_name\" =~ /$broker.*/ AND $timeFilter GROUP BY time($__interval), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU usage by pod",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Millicores" }
     ],
     "targets": [
      {
       "alias": "$tag_pod_name: usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(value) FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" =~ /^$namespace$/ AND \"pod_name\" =~ /^$side.*/ AND \"pod_name\" =~ /$broker.*/ AND $timeFilter GROUP BY time($__interval), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_pod_name: limit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(value) FROM \"cpu/limit\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" =~ /^$namespace$/ AND \"pod_name\" =~ /^$side.*/ AND \"pod_name\" =~ /$broker.*/ AND $timeFilter GROUP BY time($__interval), pod_name fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage in Percent",
     "type": "graph",
     "description": "The data usage size in percent for a Kafka broker",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"used_percent\") FROM \"t_disk\" WHERE \"path\" =~ /.*$side.*$/ AND \"path\" =~ /.*$broker$/ AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "The data usage size in bytes for a Kafka broker",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_path: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"used\") AS \"used\", max(\"total\") AS \"limit\" FROM \"t_disk\" WHERE \"path\" =~ /.*$side.*$/ AND \"path\" =~ /.*$broker$/ AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Queue Size",
     "type": "graph",
     "description": "Total number of controller requests to be sent out to brokers",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "total_queue_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"kafka_controller_ControllerChannelManager_Value\" WHERE \"name\" = 'TotalQueueSize' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event Queue Size",
     "type": "graph",
     "description": "Size of ControllerEventManager's queue. Every ControllerEvent has an associated state. When a ControllerEvent is processed, it triggers a state transition to the requested state. ControllerEvent events are managed by ControllerEventManager",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "event_queue_size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"kafka_controller_ControllerEventManager_Value\" WHERE \"name\" = 'EventQueueSize' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Event Queue Time Rate",
     "type": "graph",
     "description": "Time it takes for any event (except the Idle event) to wait in the ControllerEventManager's queue before being processed",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "event_queue_time_rate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_controller_ControllerEventManager_Count\" WHERE \"name\" = 'EventQueueTimeMs' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes In/Out",
     "type": "graph",
     "description": "Aggregate incoming/outgoing byte rate per Sampling interval",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_broker: in",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'BytesInPerSec' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_broker: out",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'BytesOutPerSec' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bytes Rejected",
     "type": "graph",
     "description": "Amount of data in bytes per Sampling interval rejected by broker",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'BytesRejectedPerSec' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ZooKeeper Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZooKeeper Session State",
     "type": "table",
     "description": "ZooKeeper session state for each broker",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 28 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"value\") AS \"zookeeper_session_state\" FROM \"kafka_server_SessionExpireListener_Value\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ZooKeeper Requests Latency",
     "type": "graph",
     "description": "Latency of ZooKeeper requests",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 28 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_ZooKeeperClientMetrics_Count\" WHERE \"name\" = 'ZooKeeperRequestLatencyMs' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "In Sync Replica (ISR)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Isr Expands Rate",
     "type": "graph",
     "description": "ISR expansion rate. If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_ReplicaManager_Count\" WHERE \"name\" = 'IsrExpandsPerSec' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Isr Shrinks Rate",
     "type": "graph",
     "description": "ISR shrink rate. If a broker goes down, ISR for some of the partitions will shrink. When that broker is up again, ISR will be expanded once the replicas are fully caught up. Other than that, the expected value for both ISR shrink rate and expansion rate is 0",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_ReplicaManager_Count\" WHERE \"name\" = 'IsrShrinksPerSec' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Rate",
     "type": "graph",
     "description": "Aggregate incoming messages rate per Sampling interval",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(mean(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'MessagesInPerSec' AND \"topic\" = '' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Fetch Requests Rate",
     "type": "graph",
     "description": "Total fetch request rate per Sampling interval",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'TotalFetchRequestsPerSec' AND \"topic\" = '' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Produce Requests Rate",
     "type": "graph",
     "description": "Total produce request rate per Sampling interval",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'TotalProduceRequestsPerSec' AND \"topic\" = '' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failed Fetch Requests Rate",
     "type": "graph",
     "description": "Fetch request rate per Sampling interval for requests that failed",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'FailedFetchRequestsPerSec' AND \"topic\" = '' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failed Produce Requests Rate",
     "type": "graph",
     "description": "Produce request rate per Sampling interval for requests that failed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(max(\"value\"), 60s)/60 FROM \"kafka_server_BrokerTopicMetrics_Count\" WHERE \"name\" = 'FailedProduceRequestsPerSec' AND \"topic\" = '' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Fetch Queue Size",
     "type": "graph",
     "description": "Size of fetch queue",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"kafka_server_Fetch_queue_size\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Queue Size",
     "type": "graph",
     "description": "Size of request queue. A congested request queue will not be able to process incoming or outgoing requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"kafka_network_RequestChannel_Value\" WHERE \"name\" = 'RequestQueueSize' AND \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Count",
     "type": "graph",
     "description": "Number of live threads, including both daemon and non-daemon threads",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"java_Threading_ThreadCount\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Total Started Thread Count",
     "type": "graph",
     "description": "Total number of threads created and also started since the JVM started",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_broker",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"gauge\") FROM \"java_Threading_TotalStartedThreadCount\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY time($__interval), \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Log Cleaner And Replica Fetcher Threads",
     "type": "table",
     "description": "Information about configured and dead Log Cleaner and Replica Fetcher threads",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"log_cleaner_threads_count\") AS \"Log Cleaner Threads Count\", max(\"log_cleaner_dead_threads_count\") AS \"Log Cleaner Dead Threads Count\", max(\"replica_fetcher_threads_count\") AS \"Replica Fetcher Threads Count\", max(\"replica_fetcher_dead_threads_count\") AS \"Replica Fetcher Dead Threads Count\" FROM \"kafka\" WHERE \"project_name\" =~ /^$namespace$/ AND \"broker\" =~ /^$side.*/ AND \"broker\" =~ /$broker/ AND $timeFilter GROUP BY \"broker\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}